# Generated by Django 5.0.6 on 2024-07-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskowner",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="taskowner",
            name="title",
            field=models.CharField(
                blank=True,
                choices=[("Mr", "Mr"), ("Mrs", "Mrs"), ("Miss", "Miss"), ("Dr", "Dr")],
                max_length=50,
                null=True,
            ),
        ),
    ]
